# Compile Godot 4
# See also: https://docs.godotengine.org/en/latest/development/compiling/compiling_for_linuxbsd.html

name: Godot build pipeline

#env:


on:
  push:
  schedule:
    # Run at 02:47 UTC each morning
    - cron: "47 2 * * *"

defaults:
  run:
    shell: bash

# If a new commit is pushed before the old one's CI has completed (on the same branch), abort previous run
#concurrency:
#  group: ${{ github.head_ref }}
#  cancel-in-progress: true

jobs:
  compile-godot:
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.artifact }}-editor

    strategy:
      fail-fast: false
      matrix:
        include:
          - id: linux
            runner: ubuntu-latest
            artifact: linux
            scons-platform: linuxbsd

          # Note: we use scons v3 (not v4), which does not recognize Visual Studio 2022 (MSVC v19.32), so we need older runner
          - id: windows
            runner: windows-2019
            artifact: windows
            scons-platform: windows

    steps:
      - name: "Clone Godot"
        run: |
          git clone https://github.com/godotengine/godot.git --depth 1 --branch master .
          echo "SHA=`git rev-parse HEAD`" >> $GITHUB_ENV
          echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV

      - name: "Check cache for Godot version ${{ env.SHORT_SHA }}"
        id: cache-godot
        uses: actions/cache@v2
        with:
          path: bin #${{ runner.temp }}/godot_bin
          key: godot-${{ runner.os }}-${{ env.SHA }}

      - name: "Linux dependencies"
        if: steps.cache-godot.outputs.cache-hit != 'true' && matrix.id == 'linux'
        run: |
          # Azure repositories are not reliable, we need to prevent azure giving us packages.
          sudo rm -f /etc/apt/sources.list.d/*
          sudo cp -f misc/ci/sources.list /etc/apt/sources.list
          sudo apt-get update
          # The actual dependencies
          sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev \
              libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev \
              libdbus-1-dev libudev-dev libxi-dev libxrandr-dev yasm xvfb wget unzip \
              llvm libspeechd-dev speech-dispatcher

      - name: "Install scons"
        if: steps.cache-godot.outputs.cache-hit != 'true'
        run: |
          pip install scons==3.1.2
          scons --version

      - name: "Compile Godot (Linux)..."
        if: steps.cache-godot.outputs.cache-hit != 'true' && matrix.id == 'linux'
        run: |
          echo "Number of cores: $(nproc)"
          scons -j$(nproc) platform=${{ matrix.scons-platform }} tools=yes target=debug bits=64
          #scons -j$(nproc) platform=${{ matrix.scons-platform }} tools=no target=release_debug bits=64

      - name: "Set up MSVC developer console"
        uses: ilammy/msvc-dev-cmd@v1
        if: matrix.id == 'windows'

      - name: "Compile Godot (Windows)..."
        if: steps.cache-godot.outputs.cache-hit != 'true' && matrix.id == 'windows'
        run: |
          cl
          scons -j2 platform=${{ matrix.scons-platform }} tools=yes target=debug mingw=no
        shell: cmd

      - name: "Make executable"
        if: steps.cache-godot.outputs.cache-hit != 'true' && matrix.id == 'linux'
        run: chmod +x bin/godot.*

      # Upload artifact also when cached (so last successful workflow always has artifact)
      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: godot-${{ matrix.artifact }}
          path: bin

      - name: "Summary"
        run: |
          godotVer=$(bin/godot.${{ matrix.scons-platform }}.tools.64 --version || true)
          echo "## Godot version: \`$godotVer\`" >> $GITHUB_STEP_SUMMARY
          echo "Built for **${{ matrix.artifact }}** from commit [\`$SHA\`](https://github.com/godotengine/godot/commit/$SHA)." >> $GITHUB_STEP_SUMMARY
