# Minimal CI workflow
# Run when someone opens a PR and adds commits to the PR (this is recognized as a push to master)
# Includes basic checks and unit/integration checks on Linux only

name: Godot artifact consumer

#env:


on:
#  push:
#  pull_request:
#    branches:
#      - master

defaults:
  run:
    shell: bash

# If a new commit is pushed before the old one's CI has completed (on the same branch), abort previous run
#concurrency:
#  group: ${{ github.head_ref }}
#  cancel-in-progress: true

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:

      - name: "Download artifact"
        # https://github.com/dawidd6/action-download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          # Downloads and unzips the artifact with {name} of the latest run of specified {workflow}
          github_token: ${{ secrets.ARTIFACT_DOWNLOADER_PAT }}
          repo: Bromeon/godot-nightly
          branch: master
          workflow: compile-godot.yml # rename: compile-godot.yml
          workflow_conclusion: success
          name: godot-linux

      # '|| true' because --version returns exit code 255, which fails the workflow
      - name: "Check Godot version"
        run: |
          chmod +x godot.linuxbsd.opt.debug.64
          ./godot.linuxbsd.opt.debug.64 --version || true

      - name: "Write summary"
        run: |
          godotVer=$(./godot.linuxbsd.opt.debug.64 --version || true)
          gitSha=$(echo $godotVer | sed -E "s/.+custom_build\.//")
          echo "### Godot version: \`$godotVer\`" >> $GITHUB_STEP_SUMMARY
          echo "Built from [this engine commit](https://github.com/godotengine/godot/commit/$gitSha)." >> $GITHUB_STEP_SUMMARY